### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by ldming-com** [VAllens/Allen.AliyunDDNSClient#1]
{System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Xml.XmlReaderSettings.CreateReader(Stream input, Uri baseUri, String baseUriString, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(Stream input, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Aliyun.Acs.Core.Regions.InternalEndpointsParser.LoadEndpointDocument()
   at Aliyun.Acs.Core.Regions.InternalEndpointsParser.GetEndpoints()
   at Aliyun.Acs.Core.Profile.DefaultProfile.GetEndpoints()
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request)
   at Aliyun.Acs.Core.DefaultAcsClient.GetAcsResponse[T](AcsRequest`1 request)
   at Allen.AliyunDDNSClient.AliyunDdnsClient.UpdateDomainRecord(String currentIp) in E:\AliyunDDNSClient\Allen.AliyunDDNSClient\AliyunDdnsClient.cs:line 79}

**Comment by ldming-com** [comment]
找到原因了，依赖包Aliyun.Acs.Core的问题，endpoints.xml文件没有指定为嵌入的资源。

**Comment by VAllens** [comment]
endpoints.xml直接放到主程序目录下即可，不需要嵌入资源。

**Comment by VAllens** [comment]
Question solving closed
